const fakeData = [
    {
        id: 1,
        title: 'Washington Avenue',
        address: 'Nasirabad H/S, Chattogram',
        bedrooms: 3,
        bathrooms: 2,
        belcony: 2,
        size: 1500,
        rent: 20000,
        service: 2000,
        deposite: '3 months',
        release: "3 months",
        floor: 'A6 (5th floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://cf.bstatic.com/xdata/images/hotel/max500/241627790.jpg?k=ccd64bd3f9a97e10df4d281984c83d3861a8b7099864c10e64f359c41c92544d&o='
    },
    {
        id: 2,
        title: 'FLAT For RENT Mogbazar',
        address: 'Wireless Gate, Mogbazar, Dhaka',
        bedrooms: 3,
        bathrooms: 2,
        belcony: 2,
        size: 1300,
        rent: 24000,
        service: 2000,
        deposite: '2 months',
        release: "2 months",
        floor: 'A4 (4th floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://cdn.jhmrad.com/wp-content/uploads/duplex-house-design-bangladesh_404038.jpg'
    },
    {
        id: 3,
        title: 'To-Let at Banasree',
        address: 'South Banasee',
        bedrooms: 3,
        bathrooms: 2,
        belcony: 1,
        size: 1500,
        rent: 15000,
        service: 1000,
        deposite: '1 months',
        release: "1 months",
        floor: 'A6 (5th floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'http://www.vistahomesbd.com/wp-content/uploads/re-listings/6dc5b_image_1.jpg'
    },
    {
        id: 4,
        title: 'Rent at Mohammadpur',
        address: 'mohammadpur mohammdia housing society',
        bedrooms: 2,
        bathrooms: 2,
        belcony: 1,
        size: 1500,
        rent: 10000,
        service: 1000,
        deposite: '3 months',
        release: "3 months",
        floor: 'A6 (5th floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://www.primeempire.com/inc/storage/app/public/category/2019-01-05-5c304dbe091c9.jpg'
    },
    {
        id: 5,
        title: 'Only female student',
        address: 'Polashi, Azimpur',
        bedrooms: 2,
        bathrooms: 2,
        belcony: 2,
        size: 1500,
        rent: 12000,
        service: 500,
        deposite: '3 months',
        release: "3 months",
        floor: 'A6 (3rd floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://cf.bstatic.com/images/hotel/max1024x768/287/287914241.jpg'
    },
    {
        id: 6,
        title: 'Rent @ Baridhara Diplomatic Zone',
        address: 'Nasirabad H/S, Chattogram',
        bedrooms: 3,
        bathrooms: 2,
        belcony: 3,
        size: 4000,
        rent: 20000,
        service: 2000,
        deposite: '3 months',
        release: "3 months",
        floor: 'A6 (5th floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://propertyfinderbd.com/public/uploads/property_thumb/bee3045878dadeefa9e6408e972857e2.jpg'
    },
    {
        id: 7,
        title: 'Flats for Rent at Rampura',
        address: 'Mohanagor project, Rampura.',
        bedrooms: 2,
        bathrooms: 2,
        belcony: 1,
        size: 1500,
        rent: 30000,
        service: 1500,
        deposite: '3 months',
        release: "3 months",
        floor: 'A3 (2nd floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://a0.muscache.com/im/pictures/7a228096-5a70-4220-8544-1d094e26f844.jpg?aki_policy=x_large'
    },
    {
        id: 8,
        title: 'Flats for Rent at Gulshan',
        address: 'Plot # 5, Road # 14, Gulshan-1, Dhaka',
        bedrooms: 3,
        bathrooms: 2,
        belcony: 4,
        size: 2260,
        rent: 55000,
        service: 2000,
        deposite: '3 months',
        release: "3 months",
        floor: 'A6 (3rd floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'http://www.vannam.in/wp-content/uploads/photo-gallery/Exterior54.jpg'
    },
    {
        id: 9,
        title: 'Flats for Rent at Uttara',
        address: ' h#28, r#14, Sector# 12, Uttara',
        bedrooms: 1,
        bathrooms: 1,
        belcony: 0,
        size: 1500,
        rent: 9000,
        service: 500,
        deposite: '3 months',
        release: "3 months",
        floor: 'A6 (6th floor)',
        details: '',
        facilities: 'Gas, Generatoe, 24/7 water, Lift',
        available: '1-June-2021',
        contact: '90846322945',
        image: 'https://res.cloudinary.com/dccloudinary/image/upload/gallery/space-apartments1/1586241784Pey9c.jpg'
    },


]
export default fakeData;